### ISSUE TITLE
ctf_sec - Decimal conversion accounting issue in MarketCore#_processAllBatchedEpochActions

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2022-11-float-capital-judging#11]
ctf_sec

medium

# Decimal conversion accounting issue in MarketCore#_processAllBatchedEpochActions

## Summary

Decimal conversion accounting has issue in MarketCore#_processAllBatchedEpochActions

## Vulnerability Detail

The PoolToken has a decimal 18, but chainlink price feed may have decimal of 8 or 18,

The payment token may have different decimals.

Some tokens have low decimals (e.g. USDC has 6). Even more extreme, some tokens like [Gemini USD](https://etherscan.io/token/0x056Fd409E1d7A124BD7017459dFEa2F387b6d5Cd?a=0x5f65f7b609678448494De4C87521CdF6cEf1e932) only have 2 decimals.

USDT has 6 decimals. [NEAR token](https://etherscan.io/token/0x85f17cf997934a597031b2e18a9ab6ebd4b9f6a4#readContract) has 24 decimals.

then without properly scaling or converting the scale of the token, the code would fail in 

MarketCore.sol#_processAllBatchedEpochActions

```solidity
    // Only if mints or redeems exist is it necessary to adjust supply and collateral.
    if (batch.paymentToken_deposit > 0 || batch.poolToken_redeem > 0) {
      changeInMarketValue_inPaymentToken = int128(batch.paymentToken_deposit) - int256(uint256(batch.poolToken_redeem).mul(price));

      int256 changeInSupply_poolToken = int256(uint256(batch.paymentToken_deposit).div(price)) - int128(batch.poolToken_redeem);

      pool.batchedAmount[associatedEpochIndex & 1] = BatchedActions(0, 0);

      _handleChangeInPoolTokensTotalSupply(poolToken, changeInSupply_poolToken);
    }
```

the code can just underflow:

batch.paymentToken_deposit could be 1000 * 10e6 (6 decimal token)

batch.poolToken_redeem = 900 * 10e18 (18 decimals) * 11 * 10e8 (chainlink price has 8 decimals)

clearly, the code below revert in underflow.

```solidity
      int256 changeInSupply_poolToken = int256(uint256(batch.paymentToken_deposit).div(price)) - int128(batch.poolToken_redeem);
```

## Impact

value depending on the batched deposits and redeems that took place during the epoch will be incorrectly updated.

## Code Snippet

https://github.com/sherlock-audit/2022-11-float-capital/blob/main/contracts/market/template/MarketCore.sol#L563-L586

## Tool used

Manual Review

## Recommendation

I think the project should scale the token by decimal properly.

For example,

The project can change from

```solidity
changeInMarketValue_inPaymentToken = int128(batch.paymentToken_deposit) - int256(uint256(batch.poolToken_redeem).mul(price));
```

to

```solidity
paymentToken_deposit = batch.paymentToken_deposit / (10 ** PaymentToken_decimals)
poolToken_redeem = batch.poolToken_redeem / (10 ** 18)
changeInMarketValue_inPaymentToken = (paymentToken_deposit - poolToken_redeem).mul(price)
```

Duplicate of #21

**Comment by JasoonS** [comment]
https://github.com/Float-Capital/monorepo/pull/3812 more strict checks. Relevant comment: https://github.com/sherlock-audit/2022-11-float-capital/pull/10#discussion_r1035993867
