### ISSUE TITLE
8olidity - Risk of overflow

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2022-11-float-capital-judging#29]
8olidity

medium

# Risk of overflow

## Summary
Risk of overflow
## Vulnerability Detail
There are two risks of spillover
1. It uint256 type to int56 directly

`batch.poolToken_redeem` and `pric`e are doing multiplication operations that will most likely exceed the size of int256

2. Match the int128 to the int256

The small precision value decreases the large type of data, it is very likely to overflow

## Impact
Risk of overflow
## Code Snippet
https://github.com/sherlock-audit/2022-11-float-capital/blob/main/contracts/market/template/MarketCore.sol#L577
```solidity
  function _processAllBatchedEpochActions(
    uint256 associatedEpochIndex,
    PoolType poolType,
    uint256 poolTier,
    uint256 price,
    address poolToken
  ) internal returns (int256 changeInMarketValue_inPaymentToken) {
    // QUESTION: is it worth the gas saving this storage pointer - we only use 'pool' twice in this function.
    Pool storage pool = pools[poolType][poolTier];

    BatchedActions memory batch = pool.batchedAmount[associatedEpochIndex & 1];

    // Only if mints or redeems exist is it necessary to adjust supply and collateral.
    if (batch.paymentToken_deposit > 0 || batch.poolToken_redeem > 0) {
      changeInMarketValue_inPaymentToken = int128(batch.paymentToken_deposit) - int256(uint256(batch.poolToken_redeem).mul(price)); //@audit  

      int256 changeInSupply_poolToken = int256(uint256(batch.paymentToken_deposit).div(price)) - int128(batch.poolToken_redeem);

      pool.batchedAmount[associatedEpochIndex & 1] = BatchedActions(0, 0);

      _handleChangeInPoolTokensTotalSupply(poolToken, changeInSupply_poolToken);
    }
  }
```
## Tool used

Manual Review

## Recommendation
use safecast()

**Comment by JasoonS** [comment]
https://github.com/Float-Capital/monorepo/pull/3816 made this change since it didn't affect gas much, and the code looks nicer when there is less type-casting too.
