### ISSUE TITLE
ctf_sec - Unsafe downcasting operation result in unsafe number truncation.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2022-11-float-capital-judging#7]
ctf_sec

medium

# Unsafe downcasting operation result in unsafe number truncation.

## Summary

Unsafe downcasting operation result in unsafe number truncation. 

## Vulnerability Detail

The unsafe dowcasting operation from uint256 to uint128 and int128 or uint112 is used in MarketCore.sol

```solidity
uint256 fees = _calculateStabilityFees(uint256(amount).mul(int256(pools[poolType][poolTier].fixedConfig.leverage).abs()));
amount -= uint112(fees);
```

```solidity
contracts\market\template\MarketCore.sol:
  127      // Correctly account for liquidity in long and short by adding the float liquidity to the underbalanced side.
  128:     totalEffectiveLiquidityPoolType[params.underBalancedSide] += uint128(uint256(pools[PoolType.FLOAT][0].value).mul(floatPoolLeverage.abs()));
  129  

  146            poolValue +=
  147:             (((poolValue * poolFixedConfig.leverage * params.valueChange) / int128(totalEffectiveLiquidityPoolType[poolType])) -
  148                ((poolValue * poolFixedConfig.leverage * params.fundingAmount[poolType]) / (actualTotalEffectiveLiquidityForPoolType))) /

  169          if (poolType != FLOAT_TYPE)
  170:           nextTotalEffectiveLiquidityPoolType[poolType] += uint128(uint256(poolValue).mul(int256(poolFixedConfig.leverage).abs()));
  171  

  576      if (batch.paymentToken_deposit > 0 || batch.poolToken_redeem > 0) {
  577:       changeInMarketValue_inPaymentToken = int128(batch.paymentToken_deposit) - int256(uint256(batch.poolToken_redeem).mul(price));
  578  
  579:       int256 changeInSupply_poolToken = int256(uint256(batch.paymentToken_deposit).div(price)) - int128(batch.poolToken_redeem);
  580  

contracts\market\template\MarketExtended.sol:
  155      if (initPool.poolType != PoolType.FLOAT)
  156:       effectiveLiquidityForPoolType[uint256(initPool.poolType)] += uint128(MathUintFloat.mul(initialActualLiquidityForNewPool, initPool.leverage));
  157  
```

## Impact

basically, if the effectiveLiquidityForPoolType is larger than type(uint128).max, it will be trancated to type(uint128).max

the effective liquidity is used to determine how much funding and feel the floating pool is received. The number truncation from unsafe downcasting would break the accounting of the smart contract.

## Code Snippet

https://github.com/sherlock-audit/2022-11-float-capital/blob/main/contracts/market/template/MarketCore.sol#L128

https://github.com/sherlock-audit/2022-11-float-capital/blob/main/contracts/market/template/MarketCore.sol#L170

https://github.com/sherlock-audit/2022-11-float-capital/blob/main/contracts/market/template/MarketCore.sol#L147

## Tool used

Manual Review

## Recommendation

We uint256 type instead of downcasting to uint128 or int128, or use openzepplin Safe-downcasting library to make sure the unexpected truncation does not happen.

https://docs.openzeppelin.com/contracts/3.x/api/utils#SafeCast

**Comment by JasoonS** [comment]
https://github.com/Float-Capital/monorepo/pull/3817 made this change since it didn't affect gas much, and the code looks nicer when there is less type-casting too.
